### ISSUE TITLE
FileNotFoundError: Local file G:/En3d/200000.zip doesn't exist

### ISSUE THREAD

**Issue by EightiesPower** [menyifang/En3D#9]
Getting this error when running app.py:
Traceback (most recent call last):
  File "app.py", line 467, in <module>
    app = WebApp(debug_mode=False)
  File "app.py", line 141, in __init__
    MsDataset.load('3DHuman_synthetic_dataset', namespace='damo', subset_name='200000').config_kwargs[
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 284, in load
    dataset_inst = remote_dataloader_manager.load_dataset(
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\data_loader\data_loader_manager.py", line 132, in load_dataset
    oss_downloader.process()
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\data_loader\data_loader.py", line 83, in process
    self._prepare_and_download()
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\data_loader\data_loader.py", line 147, in _prepare_and_download
    self.dataset = self.data_files_manager.fetch_data_files(
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\data_files\data_files_manager.py", line 112, in fetch_data_files
    builder.download_and_prepare(
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\download\dataset_builder.py", line 293, in download_and_prepare
    self._download_and_prepare(dl_manager=dl_manager)
  File "G:\miniconda3\envs\en3d\lib\site-packages\modelscope\msdatasets\download\dataset_builder.py", line 296, in _download_and_prepare
    self.split_path_dict = dl_manager.download_and_extract(
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\download\download_manager.py", line 434, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\download\download_manager.py", line 257, in download
    downloaded_path_or_paths = map_nested(
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\utils\py_utils.py", line 511, in map_nested
    mapped = [
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\utils\py_utils.py", line 512, in <listcomp>
    _single_map_nested((function, obj, batched, batch_size, types, None, True, None))
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\utils\py_utils.py", line 380, in _single_map_nested
    return [mapped_item for batch in iter_batched(data_struct, batch_size) for mapped_item in function(batch)]
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\utils\py_utils.py", line 380, in <listcomp>
    return [mapped_item for batch in iter_batched(data_struct, batch_size) for mapped_item in function(batch)]
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\download\download_manager.py", line 313, in _download_batched
    return [
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\download\download_manager.py", line 314, in <listcomp>
    self._download_single(url_or_filename, download_config=download_config)
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\download\download_manager.py", line 323, in _download_single
    out = cached_path(url_or_filename, download_config=download_config)
  File "G:\miniconda3\envs\en3d\lib\site-packages\datasets\utils\file_utils.py", line 222, in cached_path
    raise FileNotFoundError(f"Local file {url_or_filename} doesn't exist")
FileNotFoundError: Local file G:/En3d/200000.zip doesn't exist

**Comment by johndpope** [comment]
those files are hosted on chinese provider - you can sign up without china number
I pushed a single zip files to this branch 000182.zip
https://github.com/johndpope/En3D/
